apiVersion: v1
kind: Service
metadata:
  labels:
    app: galera-cluster
  name: galera-cluster
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  selector:
    app: galera-cluster
